// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilbedlpxgntqzoyalsew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsYmVkbHB4Z250cXpveWFsc2V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MzU0ODAsImV4cCI6MjA2MTAxMTQ4MH0.IvACnrepqKvEZrz1xfovavH98i8LqXDKuvd9ESeY8_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);